### ISSUE TITLE
[FEATURE] Support for filtering alerts based on timestamp

### ISSUE THREAD

**Issue by e1Ru1o** [forta-network/forta-api#10]
## Problem
`AlertsInput` currently has support for filtering based on Date & blockNumber. There are some cases were having timestamp filtering is more powerful because you will get the exact range of alerts you need. That cannot be achieved with date filtering because when using Dates you are loosing precision about the time, so it is easy to get more alerts that the ones you need. The same doesn't happen with `blockNumber` filtering because there is a unique relation between blockNumbers & timestamps, the problem in this case is when you don't know the blocks but you have a timestamp. Having information about blocks can be difficult when dealing with different networks but in that case it is easy to use `timestamp` to verify events ordering across different networks.

## Proposed Solution
I have no details to provide about how to accomplish this feature programmatically, I just have two comments to share about how I would like it to looks like in the API. I have the following two suggestions:
1. Update `blockDateRange`. Right now the supported format to use in that range is `yyyy-mm-dd`, so changing that format to [ISO](https://en.wikipedia.org/wiki/ISO_8601) will allow developers to work with timestamps. That format seems accurate because it is the one used in the API response that contains timestamps.
2. Add a `blockTimestampRange`. Adding this will make the `blockDateRange` a bit useless, because filtering by date is a subcase of filtering by timestamp.

## Additional context

One example of situation where this filter can be useful is when:
- There is a pair of events X, Y.
- X should occur on network A before Y occurs on network B.

Having one bot emitting alerts each time event X happens we can create a bot that check if the condition above is met when event Y occurs. That bot can query all X related alerts that occurred before the timestamp when the event Y occurs and filter them out looking for the one that match the specific Y event that was found. Notice that in this case there is no information about blocks on network A when analyzing the event founded in network B.

There is one sub-case of this one when the last X event that happened before timestamp of Y is the one needed, so in that case you will be able to query only one alert and you will always get the one needed if it exists.

**Comment by mwakaba2** [comment]
@e1Ru1o filter by blockTimestampRange is available now!

[docs](https://docs.forta.network/en/latest/forta-api-reference/#definition-AlertsInput)

Here's an example of setting the range.
```javascript
{
  "input": {
    "first": 100,
    "blockTimestampRange": {
      "startTimestamp": 1651791600000,
      "endTimestamp": 1652655600000
    }
  }
}
```
