### ISSUE TITLE
[FEATURE] Total number of alerts match the query criteria

### ISSUE THREAD

**Issue by kovart** [forta-network/forta-api#17]
## Problem

I am working on a dashboard app.
The main idea of the dashboard is to create groups with specific filters and parameters.
It would be helpful If I was be able to show the total number of alerts in my filtered groups so that the user can understand how many alerts match the filter query or how many pages can be paginated. I think it can also help to see that the group contains a lot of noise.

## Proposed Solution

I think we can add something like `totalCount` to `pageInfo` field.

**Comment by mwakaba2** [comment]
hey @kovart you can now query `totalAlerts` in the `pageInfo`. This will return two fields:
```gql
pageInfo {
  totalAlerts: {
    value: (int) Total number of matching documents.
    relation: (String) Indicates whether the number of matching items in the value parameter is accurate or a lower bound. (e.g. "eq" or "gte")
  }
}


```
There is one caveat: the value will only be accurate if the query has a narrow filter criteria. If the filter is minimal (e.g. only specifying bot id), the API will most likely return the lower bound with value set to `10,000`, and the relation set to `gte`. This means there are more than 10,000 matching alerts for this particular query. 

FYI, the graphql reference docs are not updated yet. Will have that updated by end of this week.
