### ISSUE TITLE
[FEATURE] Filter alerts by severity level

### ISSUE THREAD

**Issue by mwakaba2** [forta-network/forta-api#3]
## Feature

Filter alerts by specified list of severity levels (e.g. HIGH, MEDIUM, CRITICAL)

## Proposed Solution

Add option to filter alerts by severity levels:
```
severities: ['HIGH', 'MEDIUM', 'CRITICAL']
```
The above example will filter out alerts with severity type INFO and LOW.

**Comment by mwakaba2** [comment]
Hi @anudit, you can now filter alerts by severities. 
For more info on the query input, please check out https://docs.forta.network/en/latest/forta-api-reference/#definition-AlertsInput

**Comment by anudit** [comment]
Hey @mwakaba2, Switched to the new API https://github.com/anudit/convosdk/blob/main/src/adaptors/forta.ts, Thanks!

**Comment by HedgeQuantX** [comment]
Amazing thank you guys
