### ISSUE TITLE
[MAINTENANCE] Rename all `agent` references to `bot` in Forta API 

### ISSUE THREAD

**Issue by mwakaba2** [forta-network/forta-api#8]
To reduce confusion around the term `agent`, Forta decided to use the term `bot` instead. 
This will require updating all `agent` references to `bot` in the Forta API. 

## Update plan

- [x] (API code) Add a deprecation note (1 month deadline) to agent references
- [x] (API code) Update `alerts` query to allow querying bots and filtering by bots. 
- [x] (Docs) Update all `agent references in the example queries doc + deprecation warning + remove API beta announcement
- [x] (Announcements) announce deprecation
- [x] (API code + Docs) Create PRs to remove agent references and deprecation warnings.
- [x] (Announcements) Deprecation reminder 1 week before target date
- [x] (API code + Docs) Merge/deploy PRs

@anudit @dylankilkenny @mok0230, I'll let you know when you can update your code to query `bot` instead of `agent`.

**Comment by mwakaba2** [comment]
Hi @anudit @dylankilkenny @mok0230, you can now query and filter by the term `bot/bots`. For the `alerts` query, the data field `agent` and input query parameter `agents` will be deprecated on June 1st, so please make sure to replace them with `bot/bots` before then. Please let me know if you have any concerns or questions with the timeline!

Here's an example query that requests the `bot` field.
```gql
query recentAlerts($input: AlertsInput) {
  alerts(input: $input) {
    pageInfo {
      hasNextPage
      endCursor {
        alertId
        blockNumber
      }
    }
    alerts {
      name
      protocol
      findingType
      source {
        transactionHash
        block {
          number
          chainId
        }
        bot { <-- replace "agent" with bot
          id
        }
      }
    }
  }
}
```

Here's an example query input parameter that uses `bots` instead of `agents`.
```javascript
{
  "input": {
    "first": 5,
    "createdSince": 600000,
    "chainId": 1
    "bots": [<BOT_ID_A>, <BOT_ID_B>], // replace `agents` with bots
  }
}
```

**Comment by mok0230** [comment]
Thanks @mwakaba2!

I just created this issue: https://github.com/OpenZeppelin/defender/issues/2622

Should we change all of our messaging that currently includes the term "agent" to use "bot" instead? For instance, this is our current UI when creating a forta sentinel:


![Screen Shot 2022-04-29 at 10 15 50 AM](https://user-images.githubusercontent.com/92540752/165992289-78c3e4cb-1534-4914-a0e2-3bc0cca58415.png)

**Comment by mwakaba2** [comment]
Hi @mok0230, yes please replace any mentions of "agents" with "detection bots". thank you!

**Comment by mwakaba2** [comment]
@dylankilkenny, @mok0230, @anudit I got a PR ready to remove all `agent` references. I plan to deploy tomorrow. Are you all ready or do you need more time to switch?

**Comment by dylankilkenny** [comment]
@mwakaba2 we have updated Defender to the new term. Let us know when you deploy so we can check if everything is ok on our end

**Comment by mwakaba2** [comment]
@dylankilkenny just deployed to prod.
